stages:
  - build
  - docker

variables:
  IMAGE_NAME: docker-build-optimization
  IMAGE_TAG: $CI_PIPELINE_IID

build_jar:
  stage: build
  image: maven:3.9-eclipse-temurin-21
  script:
    - cd app/build-optimization-demo
    - mvn clean package

build_docker:
  stage: docker
  image: docker:24
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -f Dockerfile.multistage -t $IMAGE_NAME:$IMAGE_TAG .
    - docker images