FROM maven:3.9-eclipse-temurin-21 AS builder

WORKDIR /app

COPY app/build-optimization-demo /app/build-optimization-demo

RUN mvn -f /app/build-optimization-demo/pom.xml clean package -DskipTests


FROM tomcat:10.1

# COPY correct WAR (NO version guessing)
COPY --from=builder \
/app/build-optimization-demo/target/build-optimization-demo-1.0.war \
/usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080