FROM maven:3.9-eclipse-temurin-21 AS builder

WORKDIR /app

COPY app/build-optimization-demo .

RUN mvn clean package -DskipTests

FROM tomcat:10.1

COPY --from=builder \
/app/target/build-optimization-demo-1.0-SNAPSHOT.war \
/usr/local/tomcat/webapps/

RUN chown -R 1000:1000 /usr/local/tomcat

USER 1000

EXPOSE 8080