sonar.projectKey=malathi-shetty_docker-build-optimization-case-study
sonar.organization=malathi-shetty

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**
sonar.coverage.exclusions=**/com/company/demo/App.java