name: Docker Build Optimization

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Jar
        run: |
          cd app/build-optimization-demo
          mvn clean package

      - name: Build Docker Image
        run: |
          docker build \
          -f Dockerfile.multistage \
          -t docker-build-optimization:${{ github.run_number }} .

      - name: Generate GitHub Report
        run: |
          mkdir -p reports

          echo "Repository: $GITHUB_REPOSITORY" > reports/github-report.txt
          echo "Workflow: $GITHUB_WORKFLOW" >> reports/github-report.txt
          echo "Run Number: $GITHUB_RUN_NUMBER" >> reports/github-report.txt

          cat reports/github-report.txt

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: github-report
          path: reports/
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/
